import { type NextPage } from "next";
import { signIn, signOut, useSession } from "next-auth/react";
import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/router";
import { api } from "~/utils/api";

const Home: NextPage = () => {
  // const hello = api.example.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <>
        <AuthShowcase />
      </>
    </>
  );
};

export default Home;

const AuthShowcase: React.FC = () => {
  const router = useRouter();
  const { data: sessionData } = useSession();

  return (
    <div className="flex flex-col justify-center">
      <button
        className=" rounded-full bg-btn-primary  px-10 py-4 uppercase tracking-widest text-white duration-200 ease-in  hover:shadow-lg hover:shadow-btn-primary/50 hover:duration-100 hover:ease-in"
        onClick={() => void router.push("/todo")}
      >
        get started
      </button>
    </div>
  );
};
